{% set setup_data = load_setup_py_data() %}
package:
  name: derep-genomes
  version: {{ setup_data['version'] }}

source:
  git_rev: {{ setup_data['version'] }}
  git_url: https://github.com/genomewalker/derep-genomes.git

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python=3.9
    - numpy>=1.17.5
    - pandas>=1.1.2
    - scipy>=1.5.2
    - dataclasses
    - networkx>=2.5
    - tqdm==4.50.0
    - PyYAML==5.3.1
    - fastANI>=1.32
    - simple-slurm
    - leidenalg>=0.8.2
    - python-igraph>=0.8.3
    - mash>=2.2.2
    - gsl==2.7
    
test:
  commands:
    - derepG -h

about:
  home: https://github.com/genomewalker/derep-genomes
  summary: "A simple genome de-replication tool with fastANI"
  license: {{ setup_data['license'] }}
  license_file: LICENSE
